project: 
  type: website

website:
  title: "Isaac Kuugaayeng"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: work-experience.qmd
        text: Work Experience
      - href: publications.qmd
        text: Publications
      - href: content.qmd
        text: Content

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual
