---
format:
  html:
    page-layout: full
    css: styles.css
    toc: false
---

<center><h1>Work Experience</h1></center>

---

**Present**

<span class="role-title">GIS Technician Intern</span>, <em>Social Planning Cowichan (SPC), Duncan, British Columbia</em>  
<p>Process LiDAR data and satellite imagery using Python, ArcGIS Pro and QGIS to analyze land use change and support Indigenous-led cedar ecosystem restoration across the Cowichan, Koksilah, and Chemainus watersheds.</p>
<p>Lead the development of a custom mobile mapping app (Xpey’ Watch) using Python scripting and ArcGIS Online tools to automate field data collection and streamline stakeholder access to localized environmental datasets.</p>
<p>Maintain ArcGIS Online spatial data infrastructure, perform QA/QC and update feature layers, manage metadata and enforce topological rules to ensure accuracy and integrity of utility and planning asset data.</p>

---

**2024**

<span class="role-title">MGEM Capstone Researcher</span>, <em>University of British Columbia</em>  
<p>Conducted shade mapping and 3D modeling of tree canopy using LiDAR and satellite data to assess its influence on building energy use on the UBC campus.</p>
<p>Created spatial models identifying priority areas for tree planting, improving urban climate resilience and contributing to a 10% increase in green space allocation.</p>

---

**2022**

<span class="role-title">Junior Technical Advisor (Contract)</span>, <em>German Development Cooperation (GIZ), Ghana</em>  
<p>Produced high-quality maps and interactive ArcGIS Dashboards to track municipal-scale land use patterns, zoning designations, and utility infrastructure projects which enhanced client decision-making.</p>
<p>Co-developed an e-learning platform and geospatial data library to enhance municipal level planning, infrastructure data sharing long-term capacity-building of planning technicians, improving consistency in infrastructure reporting.</p>
<p>Automated spatial data workflows using Python, SQL and Model Builder to enhance geoprocessing efficiency by 30%, increasing accuracy and the timeliness of infrastructure planning deliverable.</p>

---

**2021**

<span class="role-title">Planning Technician Intern</span>, <em>Physical Planning Department, Ghana</em>  
<p>Reviewed architectural and construction drawings and administered updates to ArcGIS Online utility asset data, improving municipal geodatabase accuracy for permitting and asset management.</p>
<p>Reviewed and assessed 25+ development permits and conducted field inspections to verify project compliance with zoning bylaws and land-use policies, resulting in streamlined approval timelines and increased adherence to planning standards.</p>
<p>Contributed to the design and production of spatial and settlement structure plans and high-resolution thematic maps for the Jirapa Municipality that guided policy recommendations and land use zoning aligned with municipal growth strategies using QGIS and ArcGIS.</p>

---
